In [1]:
# preamble - load all packages 

import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
import datetime

from scipy import stats
from sklearn.metrics.pairwise import euclidean_distances

sns.set(rc = {'figure.figsize':(15,8)})

import tensorflow.compat.v2 as tf
tf.enable_v2_behavior()

import tensorflow_probability as tfp

tfd = tfp.distributions

In [2]:
measles = pd.read_csv('/Users/alinmorariu/Documents/GitHub/MCMC/Stochastic epidemic models/measles_hagelloch_1861.csv')

In [3]:
measles

,case_ID,infector,date_of_prodrome,date_of_rash,date_of_death,age,gender,family_ID,class,complications,x_loc,y_loc
0,1,45.0,1861-11-21,1861-11-25,NaN,7,f,41,1,yes,142.5,100.0
1,2,45.0,1861-11-23,1861-11-27,NaN,6,f,41,1,yes,142.5,100.0
2,3,172.0,1861-11-28,1861-12-02,NaN,4,f,41,0,yes,142.5,100.0
3,4,180.0,1861-11-27,1861-11-28,NaN,13,m,61,2,yes,165.0,102.5
4,5,45.0,1861-11-22,1861-11-27,NaN,8,f,42,1,yes,145.0,120.0
...,...,...,...,...,...,...,...,...,...,...,...,...
183,184,NaN,1861-10-30,1861-11-06,NaN,13,NaN,51,2,yes,182.5,200.0
184,185,82.0,1861-12-03,1861-12-07,NaN,3,m,21,0,yes,205.0,182.5
185,186,45.0,1861-11-22,1861-11-26,NaN,6,NaN,57,0,yes,212.5,90.0
186,187,82.0,1861-12-07,1861-12-11,NaN,0,m,21,0,yes,205.0,182.5
187,188,175.0,1861-11-23,1861-11-27,NaN,1,NaN,57,0,yes,212.5,90.0

In [4]:
# represent this epidemic with a tensor 

# formating the dates 
measles['date_of_prodrome'] = pd.to_datetime(measles['date_of_prodrome'], format='%Y-%m-%d')
measles['date_of_rash'] = pd.to_datetime(measles['date_of_rash'], format='%Y-%m-%d')
measles['date_of_death'] = pd.to_datetime(measles['date_of_death'], format='%Y-%m-%d')

# fill death time - death is NaN in many cases 
measles['date_of_death'] = measles['date_of_death'].fillna(pd.to_datetime('1/1/2000'))

# to avoid imputing removal time, assume rash + 5 days
measles = measles.assign(
    date_of_removal=lambda df: df.date_of_rash + datetime.timedelta(days=5))
measles = measles.assign(date_of_removal=measles[['date_of_removal', 'date_of_death']].min(axis=1))

In [5]:
measles.head()

,case_ID,infector,date_of_prodrome,date_of_rash,date_of_death,age,gender,family_ID,class,complications,x_loc,y_loc,date_of_removal
0,1,45.0,1861-11-21,1861-11-25,2000-01-01,7,f,41,1,yes,142.5,100.0,1861-11-30
1,2,45.0,1861-11-23,1861-11-27,2000-01-01,6,f,41,1,yes,142.5,100.0,1861-12-02
2,3,172.0,1861-11-28,1861-12-02,2000-01-01,4,f,41,0,yes,142.5,100.0,1861-12-07
3,4,180.0,1861-11-27,1861-11-28,2000-01-01,13,m,61,2,yes,165.0,102.5,1861-12-03
4,5,45.0,1861-11-22,1861-11-27,2000-01-01,8,f,42,1,yes,145.0,120.0,1861-12-02

In [6]:
# get dimensions of the tensor --> N x states x T 

# N 
N = measles.case_ID.nunique()

# states 
S = 3

# T - nunique of ALL dates (infected, recovered, death)
T = measles[['date_of_prodrome', 'date_of_re  moval']].stack().nunique()

KeyError: "['date_of_re  moval'] not in index"

In [ ]:
n

In [12]:
np.linalg.det(np.array([[1, 0, 0, 0, 0],
                        [8, 2, 0, 0, 0],
                        [-9, 13, -1, 0, 0],
                        [172, 39, 332, 1/2, 0],
                        [-164, 34/5, -2, 9, 1]]))

-0.9999999999999094